# Generated by Django 5.1.1 on 2024-10-03 11:58

import cloudflare_images.field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_privyprofile'),
        ('quiz', '0010_competition_split_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_type', models.CharField(choices=[('stats', 'Stats'), ('fifty', 'Fifty')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', cloudflare_images.field.CloudflareImagesField(blank=True, null=True, upload_to='', variant='public')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='question_time_seconds',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='competition',
            name='rest_time_seconds',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='competition',
            name='allowed_hint_types',
            field=models.ManyToManyField(blank=True, related_name='allowed_competitions', to='quiz.hint'),
        ),
        migrations.AddField(
            model_name='competition',
            name='built_in_hints',
            field=models.ManyToManyField(blank=True, related_name='built_in_competitions', to='quiz.hint'),
        ),
        migrations.AddField(
            model_name='usercompetition',
            name='registered_hints',
            field=models.ManyToManyField(blank=True, to='quiz.hint'),
        ),
        migrations.CreateModel(
            name='HintAchivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.hint')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
