# Generated by Django 5.1.1 on 2024-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_hint_competition_question_time_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
