# Generated by Django 5.1.1 on 2024-10-06 09:57

from django.db import migrations, models


def seed_builtin_hints(apps, schema_editor):
    Hint = apps.get_model("quiz", "Hint")

    Hint.objects.create(
        hint_type="stats",
        title="Stats Hint",
        is_active=True,
        description="See people choices stats ",
    )

    Hint.objects.create(
        hint_type="fifty",
        title="Fifty Hint",
        is_active=True,
        description="Remove two wrong choices",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_competition_max_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="hint",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            seed_builtin_hints, reverse_code=migrations.RunPython.noop
        ),
    ]
