# Generated by Django 5.1.1 on 2024-10-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0014_alter_hintachivement_params_competitionhint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCompetitionHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.hint"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.question",
                    ),
                ),
                (
                    "user_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.usercompetition",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="usercompetition",
            name="registered_hints",
        ),
        migrations.AddField(
            model_name="usercompetition",
            name="registered_hints",
            field=models.ManyToManyField(
                blank=True, through="quiz.UserCompetitionHint", to="quiz.hint"
            ),
        ),
    ]
