# Generated by Django 5.1.1 on 2024-10-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_usercompetitionhint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompetitionhint',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
