image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cp .env.example .env
      docker compose up -d
  - command: |
      docker compose logs -f

ports:
  - port: 4444
    onOpen: open-preview
    visibility: public

# Optionally specify a Dockerfile to extend the environment
# with custom tools, dependencies, etc.
